FORMAT: 1A

# Tasks
An API to allow for the creation and completion of task items.

# Group Tasks
This is a group for single task items and the collection of tasks.

## Task [/task/{id}]
This route defines the URIs to an individual task item.

+ Parameters
    + id (number, required) - The ID of the specific task.

+ Attributes
    + id: 1 (number) - The unique identifier for this task.
    + name: Buy coffee (string, required) - The friendly name for this task.
    + created: 1476549721 (number, required) - The epoch time when this task was created.
    + completed: 1476549921 (number, optional) - The epoch time when this task was completed.

### Get Single Task [GET]
+ Response 200 (application/json)
    + Attributes (Task)

### Edit Single Task [PUT]
+ Request (application/json)
    + Attributes (Task)

+ Response 200 (application/json)
    + Attributes (Task)

### Delete Single Task [DELETE]
+ Response 204

### Complete Single Task [PATCH]
+ Request (application/json)
    + Attributes
        + completed: 1476549921 (number) 

+ Response 204

## Tasks [/tasks/]
This route is the URI for the collection of all tasks.

### Get All Tasks [GET]
+ Response 200 (application/json)
    + Attributes (array[Task])

### Create New Task [POST]
+ Request (application/json)
    + Attributes (Task)

+ Response 201 (application/json)
    + Attributes (Task)

# Group Conveniences
These are convenience services. All of this data should be gettable via RESTful endpoints. However there are often clientside perforance problems for dashboards and summary screens that need data from many different endpoints. Convenience services are an anti-pattern in RESTful design.

## Progress [/progress/]
Used for a dashboard that needs to know a bunch of information. 

### Get Progress [GET]
+ Response 200 (application/json)
    + Attributes
        + overall_incomplete_tasks: 20 (number)
        + overall_median_time_to_complete: 86400 (number)
        + weekly_progress (array)
            + (object)
                + weekly_created_tasks: 10 (number)
                + weekly_completed_tasks: 8 (number)
                + weekly_median_time_to_complete: 86400 (number)
                + weekly_tasks (array[Task])